# ----
# Site

title: Anemone Docs
url: "https://docs.anemone.cloud"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Documentation for the Anemone IoT Platform.
author:
  name: Juicymo s.r.o.
  email:
  twitter: csas_devs # twitter username without the @ symbol
social:
  name: Edition Template
  links:
    - https://www.anemone.cloud
    - https://developers.csas.cz/
    - https://github.com/Juicymo/anemone-docs-v2

# -----
# Build

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
